// src/components/Flipper/Unauthorized.vue
<template>
  <div class="hero">
    <div class="hero-overlay bg-opacity-60"></div>
    <div class="text-center hero-content text-neutral-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">
          This page requires Authorization
        </h1>
        <p class="mb-5" v-if="mode == 1">
          Skyhouse Flipper requires you to be logged into a valid discord account and a member of the skyblock.tools
          discord server.
        </p>
        <p class="mb-5" v-if="mode == 2">
          Skyhouse Flipper requires you to be a member of the skyblock.tools discord server.
        </p>
        <button class="btn btn-ghost" v-if="mode == 1">Login via discord</button>
        <button class="btn btn-ghost" v-if="mode == 2">Join discord</button>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: "Unauthorized",
    props: {
      _mode: String
    },
    data() {
      return {
        mode: this._mode
      }
    },
    mounted() {
      window.unauthorized = this;
    }
  }
</script>

<style>
  .hero {
    background-image: url("../../assets/shaderbg.webp");
    height: calc(100% - 122px);
  }

  .hero-content {
    z-index: unset !important;
  }
</style>

// src/pages/Unauthorized.tsx
import tw from 'twin.macro';
import NotLoggedInBG from '@/assets/images/shader-1.webp';
import NotInServerBG from '@/assets/images/shader-2.webp';
import { useStoreState } from 'easy-peasy';

const Unauthorized = () => {
	const privilegeLevel = useStoreState((state) => state.user.data!.privilege_level);

	return (
		<div css={[{ backgroundImage: `url(${NotLoggedInBG})`, backgroundPosition: 'center bottom' }]}>
			<div tw="text-center">
				<div tw="max-w-md">
					<h1 tw="mb-5 text-5xl font-bold">This page requires Authorization</h1>
					<p tw="mb-5 text-base">
						Skyhouse requires you to be logged into a valid discord account and a member of the skyblock.tools discord server.
					</p>
					<p tw="mb-5">
						Skyhouse requires you to be a member of the skyblock.tools discord server. If you are already a member of the server, please log out and
						log back in.
					</p>
				</div>
			</div>
		</div>
	);
};

export default Unauthorized;
