// src/pages/Unauthorized.tsx
import tw from 'twin.macro';
import NotLoggedInBG from '@/assets/images/shader-1.webp';
import NotInServerBG from '@/assets/images/shader-2.webp';
import { useStoreState } from 'easy-peasy';

const Unauthorized = () => {
	const privilegeLevel = useStoreState((state) => state.user.data!.privilege_level);

	return (
		<div css={[{ backgroundImage: `url(${NotLoggedInBG})`, backgroundPosition: 'center bottom' }]}>
			<div tw="text-center">
				<div tw="max-w-md">
					<h1 tw="mb-5 text-5xl font-bold">This page requires Authorization</h1>
					<p tw="mb-5 text-base">
						Skyhouse requires you to be logged into a valid discord account and a member of the skyblock.tools discord server.
					</p>
					<p tw="mb-5">
						Skyhouse requires you to be a member of the skyblock.tools discord server. If you are already a member of the server, please log out and
						log back in.
					</p>
				</div>
			</div>
		</div>
	);
};

export default Unauthorized;

// src/components/Auth/Unauthorized.vue
<template>
  <div class="hero" :class="mode == 1 ? 'notLoggedIn' : 'notInServer'">
    <div class="hero-overlay bg-opacity-60"></div>
    <div class="text-center hero-content text-neutral-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold">
          This page requires Authorization
        </h1>
        <p class="mb-5 text-base" v-if="mode == 1">
          Skyhouse {{ name }} requires you to be logged into a valid discord
          account and a member of the skyblock.tools discord server.
        </p>
        <p class="mb-5" v-if="mode == 2">
          Skyhouse {{ name }} requires you to be a member of the skyblock.tools
          discord server. If you are already a member of the
          server, please log out and log back in.
        </p>

        <label
          for="skyHouseLogin"
          class="btn btn-accent"
          v-if="mode == 1"
          @click="loginButton"
          >Login via discord</label
        >
        <input type="checkbox" id="skyHouseLogin" class="modal-toggle" />
        <div style="padding: 26rem" class="modal">
          <div class="modal-box">
            <div class="lds-ripple">
              <div></div>
              <div></div>
            </div>
            <p>Securely logging you in via Discord...</p>
          </div>

        </div>

        <a class="btn btn-accent" v-if="mode == 2" @click="joinDiscord">{{
          txt
        }}</a>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Unauthorized",
  props: {
    _mode: Number,
    name: String,
  },
  data() {
    return {
      mode: this._mode,
      txt: "Join Discord",
      name: this.name,
    };
  },
  created() {
    window.unauthorized = this;
  },
  methods: {
    loginButton() {
      this.$root.navbar.loginButton();
    },
    joinDiscord() {
      window.location.href = "https://discord.gg/kPGE84Gf67";
    },
  },
};
</script>

<style>
.hero {
  height: calc(100% - 60px);
}

.notLoggedIn {
  background-image: url("../../assets/shaderbg.webp");
}

.notInServer {
  background-image: url("../../assets/shader3.webp");
}

.hero-content {
  z-index: unset !important;
}
</style>
